name: PR Contribution Detector

on:
  pull_request:
  merge_group:
    types: [checks_requested]
  
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
        - name: Install Cilium CLI
          run: |
            echo author_association=${{ github.event.pull_request.author_association }}
        # - run: exit 1
  
  labeler:
    if: |
      (
        (github.event.pull_request.author_association != 'OWNER') &&
        (github.event.pull_request.author_association != 'COLLABORATOR') &&
        (github.event.pull_request.author_association != 'MEMBER')
      )
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Install Cilium CLI
        run: |
          echo author_association=${{ github.event.pull_request.author_association }}

  ghcr:
    uses: ./.github/workflows/reuse.yml
    
